name: Generate binaries on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install fuse
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y -f -o Acquire::Retries=3 fuse

    - name: configure
      run: ./configure.sh --release
      
    - name: make
      run: |
       make osc-tui-x86_64.AppImage
       ./osc-tui-x86_64.AppImage --help
      
    - uses: "actions/upload-artifact@v2"
      with:
          name: build
          path: appimage-bld/osc-tui-x86_64.AppImage
