name: Appimage Create Release Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install fuse
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y -f -o Acquire::Retries=3 fuse python

    - name: configure
      run: ./configure.sh --release
      
    - name: make
      run: make appimage-bld/osc-tui-x86_64.AppImage
      
    - name: twine
      run: |
        python -m venv env
        . .venv/bin/activate
        python -m pip install -e .
        python -m pip install --upgrade build
        python -m pip install --upgrade twine
        python -m build
        twine upload --verbose  dist/*
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PIP_TOKEN }}


    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "v24.09.0"
          prerelease: true
          title: "Fix Release"
          files: |
            LICENSE
            appimage-bld/osc-tui-x86_64.AppImage
